// 100 card phrases in the Magic register — things said aloud to someone
// present: cafés, ticket desks, shops, transit, everyday chats. Never
// P2P text messages; Magic speaks in person, not over the wire.
export const PHRASES: string[] = [
  'hello, world.',
  'Large flat white with oat milk, please.',
  "What's the soup of the day?",
  'Two tickets for the planetarium, please.',
  "Where's the lift?",
  'One myki card, please.',
  'Long time, no see.',
  'Coffee first, talk later.',
  'One shot banh mi.',
  'Table for two, please.',
  'Just browsing, thanks.',
  'Can I get that to go?',
  'Which platform for the city loop?',
  'Do you take card?',
  'A dozen dumplings, half chilli oil.',
  'Is this seat taken?',
  "I'll have what they're having.",
  'Where do I tap on?',
  'One almond croissant, warmed up.',
  'Does this go to the beach?',
  'Keep the change.',
  "What time do you close?",
  'Sparkling or still? Sparkling.',
  'Can you call me a taxi?',
  "I'm here to pick up an order.",
  'A window seat, if you have one.',
  'No onions, please.',
  'Extra hot, three-quarter full.',
  "What's good here?",
  'One adult, one child, return.',
  'Sorry to keep you waiting.',
  'Could you write that down?',
  "I'm learning Auslan.",
  'Nice to meet you.',
  'See you next week.',
  'This one, in a size medium.',
  'Do you have this in black?',
  'Just the haircut, no wash.',
  'A little shorter on the sides.',
  'Where are the fitting rooms?',
  'Can I try a sample?',
  'Two scoops — pistachio and lemon.',
  'Cone, not cup.',
  'One more, same again.',
  "That's all for today, thanks.",
  'Receipt in the bag is fine.',
  'Which way to the exit?',
  'Is there a lift to level three?',
  'The quiet carriage, please.',
  'Wake me at the last stop.',
  'One day pass, please.',
  'Is the museum free on Sundays?',
  'Student discount?',
  'Can I book for Friday night?',
  'Under the name Ravi.',
  'Party of six, around eight.',
  "We'll split the bill.",
  'Everything was lovely, thanks.',
  'Compliments to the chef.',
  'A pot of jasmine tea for the table.',
  'Medium rare, please.',
  'Is the fish today fresh?',
  'What do you recommend?',
  'Surprise me.',
  'Half sugar, less ice.',
  'Bubble tea, taro, large.',
  'One pain au chocolat, one baguette.',
  'The sourdough, sliced thick.',
  'A bunch of the yellow tulips.',
  'Something for a birthday.',
  "It's a gift — could you wrap it?",
  'Happy birthday!',
  'Congratulations, you two.',
  'Good luck tomorrow.',
  'Safe travels.',
  'Say hi to your mum for me.',
  "This round's on me.",
  'Lead the way.',
  'Give me five minutes.',
  'Walk you to the corner?',
  'The usual, please.',
  'You remembered — thank you.',
  'How was your weekend?',
  'The weather turned quick, hey?',
  'Beautiful morning for it.',
  'My dog, not my rules.',
  'Sorry, he’s friendly but muddy.',
  'Can you take our photo?',
  'One more, with the water behind us.',
  'Perfect. Thank you so much.',
  'Where did you get those shoes?',
  'Love your work.',
  'After you.',
  'No worries at all.',
  'All good, take your time.',
  'Same time next week?',
  'Catch you later.',
  'Home time.',
  'Goodnight — sleep well.',
  'Thanks for waiting.',
]
